[project]
name = "savdo-app"
version = "0.1.0"
description = "savdo.uz - Aqlli Boshqaruv Tizimi"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.115.0",
    "fastapi-cli>=0.0.4",
    "uvicorn[standard]>=0.30.0",
    "python-jose[cryptography]>=3.3.0",
    "passlib[bcrypt]>=1.7.4",
    "bcrypt==4.0.1",
    "pydantic>=2.0.0",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
